version: "3"

services:

  dockerui:
    # replace username/repo:tag with your name and image details
    image: portainer/portainer
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "9000:9000"
    #networks:
    #  - webnet

  mongo:
    #image: mongo:3.0.8 # ref. https://github.com/ParsePlatform/parse-server/issues/1913
    image: bitnami/mongodb
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 150M
    #ports:
    #  - "27017:27017"
    #networks:
    #  - webnet
    volumes:
    #  - mongo_data:/data/db
      - "mongodb_data:/bitnami/mongodb"
    #  command: "--smallfiles --logpath=/dev/null --setParameter failIndexKeyTooLong=false --rest --auth"
    #command: "--smallfiles --logpath=/dev/null --setParameter failIndexKeyTooLong=false"
    # ref. http://www.diogogmt.com/running-mongodb-with-docker-and-compose/

  mongoui:
    image: mongo-express:latest
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    #depends_on:
    #  - mongo
    ports:
      - "8081:8081"
    #networks:
    #  - webnet

  parse-server:
    image: bitnami/parse
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 150M
    depends_on:
      - mongo
    ports:
      - "1337:1337"
    #networks:
    #  - webnet
    volumes:
      - "parse_data:/bitnami/parse"
    #environment:
    #  - APP_ID=agc-parse
    #  - MASTER_KEY=agsoft_parse_server
    #  - DATABASE_URI=mongodb://mongo:27017
    #command: "--appId agc-parse --masterKey agsoft_parse_server --databaseURI mongodb://mongo:27017"

  parse-dashboard:
    image: bitnami/parse-dashboard
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    depends_on:
      - mongo
    ports:
      - "4040:4040"
    #networks:
    #  - webnet
    volumes:
      - "parse_dashboard_data:/bitnami/parse-dashboard"
    #environment:
    #  - APP_ID=agc-parse
    #  - MASTER_KEY=agsoft_parse_server
    #  - SERVER_URL=http://parse-server:1337/parse
    #command: "parse-dashboard --appId agc-parse --masterKey agsoft_parse_server --serverURL http://parse-server:1337/parse"

volumes:  
  #mongo_data:
  #  driver: local
  mongodb_data:
    driver: local
  parse_data:
    driver: local
  parse_dashboard_data:
    driver: local

#networks:
#  webnet: