version: "3"

# how to deploy:
# docker swarm init
# docker stack deploy -c parse-docker-cloud.yml agc-BaaS
# dependency: parse-dasboard.config.json

services:

  dockerui:
    # replace username/repo:tag with your name and image details
    image: portainer/portainer
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
      resources:
        limits:
        #  cpus: "0.1"
          memory: 50M
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "9000:9000"
    networks:
      - webnet

  mongo:
    image: mongo:3.0.8 # ref. https://github.com/ParsePlatform/parse-server/issues/1913
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
      resources:
        limits:
        #  cpus: "0.1"
          memory: 200M
    ports:
      - "27017:27017"
    networks:
      - webnet
    volumes:
      - mongo_data:/data/db
    #  command: "--smallfiles --logpath=/dev/null --setParameter failIndexKeyTooLong=false --rest --auth"
    command: "--smallfiles --logpath=/dev/null --setParameter failIndexKeyTooLong=false"
    # ref. http://www.diogogmt.com/running-mongodb-with-docker-and-compose/

  mongoui:
    image: mongo-express:latest
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
        #  cpus: "0.1"
          memory: 50M
    ports:
      - 8081:8081
    networks:
      - webnet

  parse:
    image: parseplatform/parse-server
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
        #  cpus: "0.1"
          memory: 200M
    ports:
      - 1337:1337
    networks:
      - webnet
    #environment:
      #- APP_ID=agc-parse
      #- MASTER_KEY=agsoft_parse_server
      #- DATABASE_URI=mongodb://mongo:27017
    command: "--appId agc-parse --masterKey agsoft_parse_server --databaseURI mongodb://mongo:27017"
  # to test - curl -X GET -H "X-Parse-Application-Id: agc-parse" -H "X-Parse-Master-Key: agsoft_parse_server" http://localhost:1337/parse/serverInfo

  dashboard:
    image: yongjhih/parse-dashboard
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.4"
          memory: 400M
    ports:
      - 4040:4040
    networks:
      - webnet
    environment:
      - APP_ID=agc-parse
      - MASTER_KEY=agsoft_parse_server
      - SERVER_URL=http://192.168.1.150:1337/parse
      - ALLOW_INSECURE_HTTP=1
      - PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=1
      - TRUST_PROXY=1
      - PARSE_DASHBOARD_TRUST_PROXY=1
      - PORT=4040
    volumes:
      - ~/parse-dashboard-config.json:/src/Parse-Dashboard/parse-dashboard-config.json
volumes:  
  mongo_data:
    driver: local
  
networks:
  webnet: