apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: parse-server
  name: parse-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: parse-server
    spec:
      containers:
      - env:
        - name: GCM_KEY
        - name: LOG_LEVEL
        - name: PRODUCTION_PASSPHRASE
        - name: PUBLIC_SERVER_URL
        - name: S3_DIRECT
        - name: GCS_DIRECT
        - name: S3_BUCKET
        - name: EMAIL_VERIFICATION_SUBJECT
        - name: GCP_KEYFILE_PATH
        - name: S3_ACCESS_KEY
        - name: DEV_PASSPHRASE
        - name: EMAIL_MODULE
        - name: FILE_KEY
        - name: JAVASCRIPT_KEY
        - name: PRODUCTION_KEY
        - name: GCP_PROJECT_ID
        - name: PORT
          value: "1337"
        - name: PRODUCTION_PFX
        - name: TESTING
        - name: DATABASE_URI
        - name: DEV_CERT
        - name: EMAIL_API_KEY
        - name: GRAPHQL_SCHEMA
        - name: EMAIL_DOMAIN
        - name: EMAIL_PASSWORD_RESET_SUBJECT
        - name: EMAIL_REPLY_TO
        - name: CLIENT_KEY
        - name: GRAPHQL_SUPPORT
        - name: LIVEQUERY_SUPPORT
        - name: SERVER_URL
          value: http://localhost:1337/parse
        - name: ALLOW_CLIENT_CLASS_CREATION
        - name: DEV_PFX
        - name: DOTNET_KEY
        - name: EMAIL_FROM
        - name: PRODUCTION_CERT
        - name: AZURE_ACCOUNT
        - name: DEV_KEY
        - name: APP_ID
          value: YOUR_APP_ID
        - name: APP_NAME
        - name: AZURE_ACCESS_KEY
        - name: AZURE_CONTAINER
        - name: FACEBOOK_APP_IDS
        - name: MASTER_KEY
          value: YOUR_MASTER_KEY
        - name: EMAIL_PASSWORD_RESET_BODY
        - name: ENABLE_ANON_USERS
        - name: LIVEQUERY_CLASSES
        - name: DEV_BUNDLE_ID
        - name: EMAIL_VERIFICATION_BODY
        - name: GCS_BUCKET
        - name: S3_SECRET_KEY
        - name: COLLECTION_PREFIX
        - name: GCM_ID
        - name: MAX_UPLOAD_SIZE
        - name: PARSE_EXPERIMENTAL_CONFIG_ENABLED
        - name: PRODUCTION_BUNDLE_ID
        - name: AZURE_DIRECT
        - name: EMAIL_DISPLAY_NAME
        - name: PARSE_MOUNT
        - name: REST_API_KEY
        - name: TRUST_PROXY
        - name: VERIFY_USER_EMAILS
        image: yongjhih/parse-server
        name: parse-server
        ports:
        - containerPort: 1337
        resources: {}
        volumeMounts:
        - mountPath: /parse/cloud
          name: parse-server-claim0
        - mountPath: /certs
          name: parse-server-claim1
        - mountPath: /parse/cloud
          name: parse-cloud-code-claim0
      restartPolicy: Always
      volumes:
      - name: parse-server-claim0
        persistentVolumeClaim:
          claimName: parse-server-claim0
      - name: parse-server-claim1
        persistentVolumeClaim:
          claimName: parse-server-claim1
      - name: parse-cloud-code-claim0
        persistentVolumeClaim:
          claimName: parse-cloud-code-claim0
status: {}
