apiVersion: v1
kind: ReplicationController
metadata:
 labels:
  name: portainer
 name: rcdockerui
spec:
 replicas: 1
 selector:
  name: web
 template:
  metadata:
   labels:
    name: web
  spec:
   containers:
   - image: portainer/portainer
     name: portainer
     ports:
     - containerPort: 9000
       hostPort: 9000