apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deploy-dockerui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portainer
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: portainer
    spec:
      containers:
        - name: portainer
          image: portainer/portainer
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - mountPath: /var/run/docker.sock
            name: socket
          ports:
            - containerPort: 9000
              protocol: TCP
              hostPort: 9000
          env:
            - name: ENV
              value: dev
      volumes:
        - name: socket
          hostPath:
           path: /var/run/docker.sock
